version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: taskflow-mysql
    restart: always
    environment:
      MYSQL_DATABASE: taskflow
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: taskflow
      MYSQL_PASSWORD: taskflow
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: taskflow-app
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
    ports:
      - "8080:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public

volumes:
  db_data:
